test:
  sessions:
    default:
      database: mln-test
      hosts:
        - localhost:27017
development:
  sessions:
    default:
      database: mln-dev
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>