test:
  sessions:
    default:
      database: alguns_patos-test
      hosts:
        - localhost:27017
development:
  sessions:
    default:
      database: alguns_patos-dev
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>